### ISSUE TITLE
How to pass in existing labels to display

### ISSUE THREAD

**Issue by tomstgeorge** [excing/flutter_autocomplete_label#1]
Hi 

Thanks for the great package, this is exactly what I need.

I'm new to Flutter so forgive me if it should be obvious, but how can I set it up so that the label field can be pre-populated with some existing labels. e.g. if the user is editing labels they have already added?

thanks

**Comment by mattar88** [comment]
same here

**Comment by excing** [comment]
Like this:

```dart
final AutocompleteLabelController _autocompleteLabelController =
      AutocompleteLabelController<String>(source: [
    "Android",
    "iOS",
    "Flutter",
    "Windows",
  ], value: [
    "Android",
    "iOS",
  ]);
```

Set an array for the `value` parameter in the AutocompleteLabelController constructor.
